apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
      name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment
    namespace: development
    labels:
        app: myapp
        app-version: '0.1'
spec:
    replicas: 1
    selector:
        matchLabels:
            app: myapp
    template:
        metadata:
            labels:
                app: myapp
                app-version: '0.1'
        spec:
            containers:
                - name: myapp
                  image: docker.io/avijitpal9/myapp:latest
                  ports:
                      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: myapp-svc
    namespace: development
    labels:
        name: myapp-svc
spec:
    type: ClusterIP
    selector:
        app: myapp
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: myapp-ingress
    namespace: development
    annotations:
         nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
        - host: myapp-dev.internal.com
          http:
            paths:
                - path: /
                  backend:
                      serviceName: myapp-svc
                      servicePort: 5000
