apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
      name: development
---
apiVersion: v1
kind: Deployment
metadata:
    name: myapp
    namesapce: development
    labels:
        app: myapp
        version: 0.1
    namespace: default
spec:
    replicas: 3
    selector:
        matchLabels:
            app: myapp
    template:
        metadata:
            labels:
                app: myapp
                version: 0.1
        spec:
            containers:
                - name: myapp
                  image: docker.io/avijitpal9/myapp:latest
                  ports:
                      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: myapp-svc
    namesapce: development
    labels:
        name: myapp-svc
spec:
    type: NodePort
    selector:
        app: myapp
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
          nodePort: 5000
